apiVersion: v1
kind: Service
metadata:
  name: frontend-lb
  namespace: valerix
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-name: "valerix-app-live"
    service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
    service.beta.kubernetes.io/do-loadbalancer-algorithm: "round_robin"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-port: "3000"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-protocol: "http"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-path: "/"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-check-interval-seconds: "10"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-response-timeout-seconds: "5"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-healthy-threshold: "2"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-unhealthy-threshold: "2"
    service.beta.kubernetes.io/do-loadbalancer-size: "lb-small"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
